function SpawnRegions()
	return {
		{ name = "Muldraugh, KY", file = "media/maps/Muldraugh, KY/spawnpoints.lua" },
		{ name = "Riverside, KY", file = "media/maps/Riverside, KY/spawnpoints.lua" },
		{ name = "Rosewood, KY", file = "media/maps/Rosewood, KY/spawnpoints.lua" },
		{ name = "West Point, KY", file = "media/maps/West Point, KY/spawnpoints.lua" },
		{ name = "ModTemplateWorld1", file = "media/maps/ModTemplateWorld1/spawnpoints.lua" },
		{ name = "ModTemplateWorld2", file = "media/maps/ModTemplateWorld2/spawnpoints.lua" },
		{ name = "Westoutskirts-shippingCo", file = "media/maps/Westoutskirts-shippingCo/spawnpoints.lua" },
		{ name = "Trelai_4x4", file = "media/maps/Trelai_4x4/spawnpoints.lua" },
		{ name = "Trelai_spawns", file = "media/maps/Trelai_spawns/spawnpoints.lua" },
		{ name = "Trelai_storyspawn", file = "media/maps/Trelai_storyspawn/spawnpoints.lua" },
		{ name = "Ashenwood", file = "media/maps/Ashenwood/spawnpoints.lua" },
		{ name = "BedfordFalls", file = "media/maps/BedfordFalls/spawnpoints.lua" },
		{ name = "North", file = "media/maps/North/spawnpoints.lua" },
		{ name = "South", file = "media/maps/South/spawnpoints.lua" },
		{ name = "West", file = "media/maps/West/spawnpoints.lua" },
		{ name = "Bendys Bunker v2", file = "media/maps/Bendys Bunker v2/spawnpoints.lua" },
		{ name = "Blackwood", file = "media/maps/Blackwood/spawnpoints.lua" },
		{ name = "Blueberry", file = "media/maps/Blueberry/spawnpoints.lua" },
		{ name = "Breakpoint", file = "media/maps/Breakpoint/spawnpoints.lua" },
		{ name = "BuildItCell1", file = "media/maps/BuildItCell1/spawnpoints.lua" },
		{ name = "BuildItCell2", file = "media/maps/BuildItCell2/spawnpoints.lua" },
		{ name = "LastMinutePrepper", file = "media/maps/LastMinutePrepper/spawnpoints.lua" },
		{ name = "LastMinutePrepperReloaded", file = "media/maps/LastMinutePrepperReloaded/spawnpoints.lua" },
		{ name = "CONRTF", file = "media/maps/CONRTF/spawnpoints.lua" },
		{ name = "Canvasback", file = "media/maps/Canvasback/spawnpoints.lua" },
		{ name = "Cedar Hill", file = "media/maps/Cedar Hill/spawnpoints.lua" },
		{ name = "CherokeeLake", file = "media/maps/CherokeeLake/spawnpoints.lua" },
		{ name = "Chestown", file = "media/maps/Chestown/spawnpoints.lua" },
		{ name = "Chinatown_EX", file = "media/maps/Chinatown_EX/spawnpoints.lua" },
		{ name = "Chinatown", file = "media/maps/Chinatown/spawnpoints.lua" },
		{ name = "CorOTRroad", file = "media/maps/CorOTRroad/spawnpoints.lua" },
		{ name = "Riverdeltabase", file = "media/maps/Riverdeltabase/spawnpoints.lua" },
		{ name = "Dirkerdam", file = "media/maps/Dirkerdam/spawnpoints.lua" },
		{ name = "Dirkerdam west", file = "media/maps/Dirkerdam west/spawnpoints.lua" },
		{ name = "Dirkerdam_Spawns", file = "media/maps/Dirkerdam_Spawns/spawnpoints.lua" },
		{ name = "Florius", file = "media/maps/Florius/spawnpoints.lua" },
		{ name = "Pertville", file = "media/maps/Pertville/spawnpoints.lua" },
		{ name = "Tashtego", file = "media/maps/Tashtego/spawnpoints.lua" },
		{ name = "EVAC_Louisville", file = "media/maps/EVAC_Louisville/spawnpoints.lua" },
		{ name = "EVAC_Muldraugh", file = "media/maps/EVAC_Muldraugh/spawnpoints.lua" },
		{ name = "EdsAutoSalvage", file = "media/maps/EdsAutoSalvage/spawnpoints.lua" },
		{ name = "Elysium_Island", file = "media/maps/Elysium_Island/spawnpoints.lua" },
		{ name = "Lone", file = "media/maps/Lone/spawnpoints.lua" },
		{ name = "Fort_Boonesborough", file = "media/maps/Fort_Boonesborough/spawnpoints.lua" },
		{ name = "FortRedstone", file = "media/maps/FortRedstone/spawnpoints.lua" },
		{ name = "Fort Rock Ridge", file = "media/maps/Fort Rock Ridge/spawnpoints.lua" },
		{ name = "Fort Waterfront", file = "media/maps/Fort Waterfront/spawnpoints.lua" },
		{ name = "Glenport", file = "media/maps/Glenport/spawnpoints.lua" },
		{ name = "Grapeseed", file = "media/maps/Grapeseed/spawnpoints.lua" },
		{ name = "Greenleaf", file = "media/maps/Greenleaf/spawnpoints.lua" },
		{ name = "Greenport", file = "media/maps/Greenport/spawnpoints.lua" },
		{ name = "hq", file = "media/maps/hq/spawnpoints.lua" },
		{ name = "Hyrule County", file = "media/maps/Hyrule County/spawnpoints.lua" },
		{ name = "FortRedstone_map", file = "media/maps/FortRedstone_map/spawnpoints.lua" },
		{ name = "InGameMaps_Main", file = "media/maps/InGameMaps_Main/spawnpoints.lua" },
		{ name = "Glenport_map", file = "media/maps/Glenport_map/spawnpoints.lua" },
		{ name = "InGameMaps_Vanilla", file = "media/maps/InGameMaps_Vanilla/spawnpoints.lua" },
		{ name = "west_point_expansion_map", file = "media/maps/west_point_expansion_map/spawnpoints.lua" },
		{ name = "west_point_expansion", file = "media/maps/west_point_expansion/spawnpoints.lua" },
		{ name = "lvinternationalairport", file = "media/maps/lvinternationalairport/spawnpoints.lua" },
		{ name = "LCV2", file = "media/maps/LCV2/spawnpoints.lua" },
		{ name = "li_township", file = "media/maps/li_township/spawnpoints.lua" },
		{ name = "LittleTownship", file = "media/maps/LittleTownship/spawnpoints.lua" },
		{ name = "HouseLuisMatrioshka", file = "media/maps/HouseLuisMatrioshka/spawnpoints.lua" },
		{ name = "Louisville_Quarantine_Zone", file = "media/maps/Louisville_Quarantine_Zone/spawnpoints.lua" },
		{ name = "Louisville_Riverboat", file = "media/maps/Louisville_Riverboat/spawnpoints.lua" },
		{ name = "lvharbor", file = "media/maps/lvharbor/spawnpoints.lua" },
		{ name = "MREX", file = "media/maps/MREX/spawnpoints.lua" },
		{ name = "militaryairport", file = "media/maps/militaryairport/spawnpoints.lua" },
		{ name = "Military Fuel Depot", file = "media/maps/Military Fuel Depot/spawnpoints.lua" },
		{ name = "MonmouthCounty", file = "media/maps/MonmouthCounty/spawnpoints.lua" },
		{ name = "Muldraugh Fire Department", file = "media/maps/Muldraugh Fire Department/spawnpoints.lua" },
		{ name = "Muldraugh Military Base", file = "media/maps/Muldraugh Military Base/spawnpoints.lua" },
		{ name = "NSCarWorkshop", file = "media/maps/NSCarWorkshop/spawnpoints.lua" },
		{ name = "newtersh", file = "media/maps/newtersh/spawnpoints.lua" },
		{ name = "newtersh_northroad", file = "media/maps/newtersh_northroad/spawnpoints.lua" },
		{ name = "NewTersh_Ext_RoadToKnox", file = "media/maps/NewTersh_Ext_RoadToKnox/spawnpoints.lua" },
		{ name = "NewTersh_Muldraugh_Connection", file = "media/maps/NewTersh_Muldraugh_Connection/spawnpoints.lua" },
		{ name = "NewEkron", file = "media/maps/NewEkron/spawnpoints.lua" },
		{ name = "orchidwood", file = "media/maps/orchidwood/spawnpoints.lua" },
		{ name = "Otr", file = "media/maps/Otr/spawnpoints.lua" },
		{ name = "Over the River - Secondary Route", file = "media/maps/Over the River - Secondary Route/spawnpoints.lua" },
		{ name = "OverlookHotel", file = "media/maps/OverlookHotel/spawnpoints.lua" },
		{ name = "Petroville", file = "media/maps/Petroville/spawnpoints.lua" },
		{ name = "Pitstop", file = "media/maps/Pitstop/spawnpoints.lua" },
		{ name = "RabbitHashKY", file = "media/maps/RabbitHashKY/spawnpoints.lua" },
		{ name = "RavenCreek", file = "media/maps/RavenCreek/spawnpoints.lua" },
		{ name = "RedstoneRaceway", file = "media/maps/RedstoneRaceway/spawnpoints.lua" },
		{ name = "researchbase", file = "media/maps/researchbase/spawnpoints.lua" },
		{ name = "researchbaseroad", file = "media/maps/researchbaseroad/spawnpoints.lua" },
		{ name = "rbr_road", file = "media/maps/rbr_road/spawnpoints.lua" },
		{ name = "Riverside Fire Department", file = "media/maps/Riverside Fire Department/spawnpoints.lua" },
		{ name = "riversidemansion", file = "media/maps/riversidemansion/spawnpoints.lua" },
		{ name = "Road from Monmouth County to Bedford Falls", file = "media/maps/Road from Monmouth County to Bedford Falls/spawnpoints.lua" },
		{ name = "pz_rosewoodexp_map", file = "media/maps/pz_rosewoodexp_map/spawnpoints.lua" },
		{ name = "Rosewood VHS Store", file = "media/maps/Rosewood VHS Store/spawnpoints.lua" },
		{ name = "SZ_Battlefield_Louisville_Airfield", file = "media/maps/SZ_Battlefield_Louisville_Airfield/spawnpoints.lua" },
		{ name = "SZ_Battlefield_Louisville_Hospital", file = "media/maps/SZ_Battlefield_Louisville_Hospital/spawnpoints.lua" },
		{ name = "SZ_Battlefield_Louisville_Stadium", file = "media/maps/SZ_Battlefield_Louisville_Stadium/spawnpoints.lua" },
		{ name = "SZ_Camp_Deerhead", file = "media/maps/SZ_Camp_Deerhead/spawnpoints.lua" },
		{ name = "SZ_Checkpoint_1", file = "media/maps/SZ_Checkpoint_1/spawnpoints.lua" },
		{ name = "SZ_Checkpoint_2", file = "media/maps/SZ_Checkpoint_2/spawnpoints.lua" },
		{ name = "SZ_Checkpoint_3", file = "media/maps/SZ_Checkpoint_3/spawnpoints.lua" },
		{ name = "SZ_Checkpoint_4", file = "media/maps/SZ_Checkpoint_4/spawnpoints.lua" },
		{ name = "SZ_Checkpoint_5", file = "media/maps/SZ_Checkpoint_5/spawnpoints.lua" },
		{ name = "SZ_Checkpoint_6", file = "media/maps/SZ_Checkpoint_6/spawnpoints.lua" },
		{ name = "SZ_Checkpoint_7", file = "media/maps/SZ_Checkpoint_7/spawnpoints.lua" },
		{ name = "SZ_Checkpoint_8", file = "media/maps/SZ_Checkpoint_8/spawnpoints.lua" },
		{ name = "SZ_EVAC_Louisville", file = "media/maps/SZ_EVAC_Louisville/spawnpoints.lua" },
		{ name = "SZ_MarchRidge_Research", file = "media/maps/SZ_MarchRidge_Research/spawnpoints.lua" },
		{ name = "SZ_Muldraugh_Crossing_Blockade", file = "media/maps/SZ_Muldraugh_Crossing_Blockade/spawnpoints.lua" },
		{ name = "SZ_EVAC_Muldraugh", file = "media/maps/SZ_EVAC_Muldraugh/spawnpoints.lua" },
		{ name = "SZ_Muldraugh_Blockade", file = "media/maps/SZ_Muldraugh_Blockade/spawnpoints.lua" },
		{ name = "SZ_Rosewood_Fossoil_Blockade", file = "media/maps/SZ_Rosewood_Fossoil_Blockade/spawnpoints.lua" },
		{ name = "SZ_Rosewood_Prison", file = "media/maps/SZ_Rosewood_Prison/spawnpoints.lua" },
		{ name = "SZ_TheMall_Resistance", file = "media/maps/SZ_TheMall_Resistance/spawnpoints.lua" },
		{ name = "SZ_Westpoint_Bridge_out", file = "media/maps/SZ_Westpoint_Bridge_out/spawnpoints.lua" },
		{ name = "Seaside", file = "media/maps/Seaside/spawnpoints.lua" },
		{ name = "SecretZ_Core", file = "media/maps/SecretZ_Core/spawnpoints.lua" },
		{ name = "SecretZ_Core_v2", file = "media/maps/SecretZ_Core_v2/spawnpoints.lua" },
		{ name = "SecretZ_Core_v2_5", file = "media/maps/SecretZ_Core_v2_5/spawnpoints.lua" },
		{ name = "Hunter'sBase_map", file = "media/maps/Hunter'sBase_map/spawnpoints.lua" },
		{ name = "ranger's_homestead_map", file = "media/maps/ranger's_homestead_map/spawnpoints.lua" },
		{ name = "valutechamusementpark", file = "media/maps/valutechamusementpark/spawnpoints.lua" },
		{ name = "Southwood2.0", file = "media/maps/Southwood2.0/spawnpoints.lua" },
		{ name = "spencermansionlootable", file = "media/maps/spencermansionlootable/spawnpoints.lua" },
		{ name = "Springwood", file = "media/maps/Springwood/spawnpoints.lua" },
		{ name = "St Paulo", file = "media/maps/St Paulo/spawnpoints.lua" },
		{ name = "Tandil", file = "media/maps/Tandil/spawnpoints.lua" },
		{ name = "The Compound", file = "media/maps/The Compound/spawnpoints.lua" },
		{ name = "The Frigate", file = "media/maps/The Frigate/spawnpoints.lua" },
		{ name = "The Mall FIXED - use this", file = "media/maps/The Mall FIXED - use this/spawnpoints.lua" },
		{ name = "PrisonTWD", file = "media/maps/PrisonTWD/spawnpoints.lua" },
		{ name = "The Yacht", file = "media/maps/The Yacht/spawnpoints.lua" },
		{ name = "The Museum", file = "media/maps/The Museum/spawnpoints.lua" },
		{ name = "Tugaland", file = "media/maps/Tugaland/spawnpoints.lua" },
		{ name = "UncleRedsBunker", file = "media/maps/UncleRedsBunker/spawnpoints.lua" },
		{ name = "UncleRedsBunkerRedux", file = "media/maps/UncleRedsBunkerRedux/spawnpoints.lua" },
		{ name = "Utopia", file = "media/maps/Utopia/spawnpoints.lua" },
		{ name = "Walnut_ridge", file = "media/maps/Walnut_ridge/spawnpoints.lua" },
		{ name = "Waterlocked Pharmaceutical Factory", file = "media/maps/Waterlocked Pharmaceutical Factory/spawnpoints.lua" },
		{ name = "WestPointExpansionFix", file = "media/maps/WestPointExpansionFix/spawnpoints.lua" },
		{ name = "West Point Fire Department", file = "media/maps/West Point Fire Department/spawnpoints.lua" },
		{ name = "WestPointGatedCommunity", file = "media/maps/WestPointGatedCommunity/spawnpoints.lua" },
		{ name = "WestPointTrailerParkAndVhsStore", file = "media/maps/WestPointTrailerParkAndVhsStore/spawnpoints.lua" },
		{ name = "Westwood", file = "media/maps/Westwood/spawnpoints.lua" },
		{ name = "weyhausen", file = "media/maps/weyhausen/spawnpoints.lua" },
		{ name = "Wilbore", file = "media/maps/Wilbore/spawnpoints.lua" },
		{ name = "Winchester, KY", file = "media/maps/Winchester, KY/spawnpoints.lua" },
		{ name = "Xonics Mega Mall", file = "media/maps/Xonics Mega Mall/spawnpoints.lua" },
		{ name = "Xonics Mega Mall Exterior", file = "media/maps/Xonics Mega Mall Exterior/spawnpoints.lua" },
		{ name = "Xonics Mega Mall Interior", file = "media/maps/Xonics Mega Mall Interior/spawnpoints.lua" },
		{ name = "Xonics Mega Mall Roof", file = "media/maps/Xonics Mega Mall Roof/spawnpoints.lua" },
		{ name = "vehicle_interior", file = "media/maps/vehicle_interior/spawnpoints.lua" },
		{ name = "adelaide", file = "media/maps/adelaide/spawnpoints.lua" },
		{ name = "ayrton", file = "media/maps/ayrton/spawnpoints.lua" },
		{ name = "bdizzle", file = "media/maps/bdizzle/spawnpoints.lua" },
		{ name = "ben", file = "media/maps/ben/spawnpoints.lua" },
		{ name = "bonnefoy", file = "media/maps/bonnefoy/spawnpoints.lua" },
		{ name = "cherbourg", file = "media/maps/cherbourg/spawnpoints.lua" },
		{ name = "claire", file = "media/maps/claire/spawnpoints.lua" },
		{ name = "daniel", file = "media/maps/daniel/spawnpoints.lua" },
		{ name = "darin", file = "media/maps/darin/spawnpoints.lua" },
		{ name = "david", file = "media/maps/david/spawnpoints.lua" },
		{ name = "Debug", file = "media/maps/Debug/spawnpoints.lua" },
		{ name = "DialloBoubakar", file = "media/maps/DialloBoubakar/spawnpoints.lua" },
		{ name = "didier", file = "media/maps/didier/spawnpoints.lua" },
		{ name = "iltud", file = "media/maps/iltud/spawnpoints.lua" },
		{ name = "johan", file = "media/maps/johan/spawnpoints.lua" },
		{ name = "julien", file = "media/maps/julien/spawnpoints.lua" },
		{ name = "kate", file = "media/maps/kate/spawnpoints.lua" },
		{ name = "legumanigo", file = "media/maps/legumanigo/spawnpoints.lua" },
		{ name = "perle", file = "media/maps/perle/spawnpoints.lua" },
		{ name = "ray", file = "media/maps/ray/spawnpoints.lua" },
		{ name = "romain", file = "media/maps/romain/spawnpoints.lua" },
		{ name = "simeon", file = "media/maps/simeon/spawnpoints.lua" },
		{ name = "Yemmlie", file = "media/maps/Yemmlie/spawnpoints.lua" },
		{ name = "VehicleSpawnZonesExpandedRedRace", file = "media/maps/VehicleSpawnZonesExpandedRedRace/spawnpoints.lua" },
		{ name = "MotoriousExpandedSpawnZones", file = "media/maps/MotoriousExpandedSpawnZones/spawnpoints.lua" },
	}
end
